image: gcc:10.2

pipelines:
  default:
    - parallel:
        - step:
            name: test
            script:
              - cd common
              - CXX=g++ ./build_unit.sh
              - ./unittest
