#ifndef testbed_input_H__
#define testbed_input_H__

enum InputKeyId
{
	INPUT_ID_ESC,
	INPUT_ID_LEFT,
	INPUT_ID_RIGHT,
	INPUT_ID_DOWN,
	INPUT_ID_UP,
	INPUT_ID_ALT_LEFT,
	INPUT_ID_ALT_RIGHT,
	INPUT_ID_ALT_DOWN,
	INPUT_ID_ALT_UP,
	INPUT_ID_ACTION,
	INPUT_ID_OPTION_1,
	INPUT_ID_OPTION_2,
	INPUT_ID_OPTION_3,
	INPUT_ID_OPTION_4,

	INPUT_ID_COUNT,
};

enum InputKeyMask
{
	INPUT_MASK_ESC          = 1 << INPUT_ID_ESC,
	INPUT_MASK_LEFT         = 1 << INPUT_ID_LEFT,
	INPUT_MASK_RIGHT        = 1 << INPUT_ID_RIGHT,
	INPUT_MASK_DOWN         = 1 << INPUT_ID_DOWN,
	INPUT_MASK_UP           = 1 << INPUT_ID_UP,
	INPUT_MASK_ALT_LEFT     = 1 << INPUT_ID_ALT_LEFT,
	INPUT_MASK_ALT_RIGHT    = 1 << INPUT_ID_ALT_RIGHT,
	INPUT_MASK_ALT_DOWN     = 1 << INPUT_ID_ALT_DOWN,
	INPUT_MASK_ALT_UP       = 1 << INPUT_ID_ALT_UP,
	INPUT_MASK_ACTION       = 1 << INPUT_ID_ACTION,
	INPUT_MASK_OPTION_1     = 1 << INPUT_ID_OPTION_1,
	INPUT_MASK_OPTION_2     = 1 << INPUT_ID_OPTION_2,
	INPUT_MASK_OPTION_3     = 1 << INPUT_ID_OPTION_3,
	INPUT_MASK_OPTION_4     = 1 << INPUT_ID_OPTION_4,

	INPUT_MASK_FORCE_TYPE   = 0xffffffffU
};

#endif // testbed_input_H__
